### ISSUE TITLE
Call volume still too low

### ISSUE THREAD

**Issue by Chris56** [zeekoe/MICGAIN-s5neolte#1]
Is there any documentation on the very many different values in mixer_paths_0.xml ?
How did you find out about the many changes values?
Which value do I have to increase to raise the call mic volume (also for signal messenger calls the volume is too low).
Voice recording through mic is ok.
Bluetooth headset is ok.
I am on android 10.
Thanks n advance. 
Chris

**Comment by zeekoe** [comment]
Hi Chris,

Nice to hear from you, good that it is of (a bit) help. I can't really remember the details, and I don't actually use my S5 a lot anymore.

What you can try is:

Get the original mixer_paths_0.xml. Either from your device (remove addon.d/60-mixer.sh, install an OS update - and you will have the original one again, I think), or from a LineageOS zip file. Compare it to the one in here with a diff tool (I use IntelliJ IDEA community edition which works fine and is free but is a bit big, something like kdiff3 or windiff might also do the trick). This way you can see what I have changed.
I can't remember if there was documentation. I think I just tried things. It was a bit of fiddling to find out what the max values of some properties were (some might have been 127, some might have been 2, but others might have been higher). I just tried a lot. On a rooted phone, so I could easily change the files, uploading and downloading them using adb and then edit them on a computer. Then reboot, then try calling another phone... and again.

One problem that I have is that with a headset on a MS Teams call it's not loud enough - while it is loud enough on the main microphone. If you would manage to fix that I would like to have it! Don't have the time/priority to fiddle with that now.

By the way, it might be that things have changed, I think mine was for Android 8 - so the diff is especially important as you are now using 10.

Does that get you somewhere?

**Comment by zeekoe** [comment]
I now see there are two forks with additional modifications, check them out:
https://github.com/NerdyProjects/MICGAIN-s5neolte
https://github.com/DougInAMug/MICGAIN-s5neolte

**Comment by zeekoe** [comment]
I merged NerdyProjects' changes. He fixed the "narrowband" volume. My guess is that it's for different kinds of mobile networks, others than what I was using. It might solve your issue rightaway.
